[project]
packages = [
    "php83",
    "php83Extensions.composer",
    "php83Extensions.mbstring",
    "php83Extensions.pdo",
    "php83Extensions.pdo_pgsql",
    "php83Extensions.redis",
    "php83Extensions.xml",
    "php83Extensions.curl",
    "php83Extensions.openssl",
    "php83Extensions.fileinfo",
    "nodejs-20_x"
]

[phases.setup]
commands = [
    "npm install",
    "npm run build"
]

[phases.build]
commands = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "php artisan migrate --force"
]

start_cmd = "php -S 0.0.0.0:$PORT -t public"
