[phases.build]
commands = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "php artisan migrate --force"
]

[phases.setup]
commands = [
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get install -y nodejs",
    "npm install",
    "npm run build"
]

start_cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
